
[context.production.environment]
    ELEVENTY_ENV = "production"
    NODE_ENV = "production"
    NODE_VERSION = "17"
    TZ = "Europe/Zurich"

# 404s
[[redirects]]
    from = "*"
    to = "/404"
    status = 404
