name: Trigger Netlify Build
on:
  schedule:
    - cron: '0 7,14,21 * * *' # https://crontab.guru/#0_7,14,21_*_*_*
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
